CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(64) NOT NULL DEFAULT 'Administrator',
  password_hash CHAR(64) NOT NULL,
  password_salt CHAR(32) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
  token_hash CHAR(64) NOT NULL PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_sessions_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  INDEX idx_sessions_expires_at (expires_at)
);

CREATE TABLE eggs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  author VARCHAR(255) NULL,
  description TEXT NULL,
  docker_image VARCHAR(512) NOT NULL,
  startup_command TEXT NOT NULL,
  config JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE egg_variables (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  egg_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  env_variable VARCHAR(255) NOT NULL,
  default_value TEXT NULL,
  user_viewable BOOLEAN NOT NULL DEFAULT TRUE,
  user_editable BOOLEAN NOT NULL DEFAULT TRUE,
  rules TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_egg_variables_egg_id FOREIGN KEY (egg_id) REFERENCES eggs (id) ON DELETE CASCADE,
  UNIQUE KEY uniq_egg_variable (egg_id, env_variable)
);

CREATE TABLE servers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  egg_id BIGINT UNSIGNED NULL,
  name VARCHAR(255) NOT NULL,
  status VARCHAR(64) NOT NULL,
  players INT UNSIGNED NOT NULL DEFAULT 0,
  ram_usage INT UNSIGNED NOT NULL DEFAULT 0,
  cpu_usage INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_servers_egg_id FOREIGN KEY (egg_id) REFERENCES eggs (id) ON DELETE SET NULL
);
