// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzyldgvxlbnorwgtzdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eWxkZ3Z4bGJub3J3Z3R6ZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxMTc2MzEsImV4cCI6MjA0OTY5MzYzMX0.1f9pmGVXtwRB_4neDGdtC0FMH_Ro6Amo9RwHlXb8xa4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);